### ISSUE TITLE
Some questions about training NNUE.

### ISSUE THREAD

**Issue by PikaCat-OuO** [fairy-stockfish/variant-nnue-pytorch#16]
May I ask the difference between the following data generation process and the final NNUE play strength?
A. 100M position of depth 10
B. 100M position of depth 20
C. 1B position of depth 10
D. 1B position of depth 20
Let me guess, technically speaking, D > B > C > A ?

Using the latest NNUE file to generate new training data, it's like the process of bootstrapping, will it cause **Bootstrapping Error** problem? i.e. If the latest NNUE weights and biases have weaknesses in some situations they will get amplified in the late nets. 

BTW, from your point of view, how much does the final NNUE file trained with depth 20 stronger than depth 10? What's the play strength difference between 1B position training data using the classical evaluation of depth 20 and 1B position with the latest NNUE net evaluation of depth 10?

Furthermore, suppose I can't hold 1B position in the RAM at a time, I split them into 3 parts, 400M 300M 300M.
How much player strength difference it will be do you think in the following training process?
A. Training 1B at a time for 400 epochs.
B. Training 400M at a time for 400 epochs, continue training the following 300M position for 400 epochs and continue training the rest 300M for 400 epochs.

Finally, If I cause any inconvenience to you for taking your precious time to answer these questions, I am so sorry to bother you these days. ( >︿< )

**Comment by ianfab** [comment]
> May I ask the difference between the following data generation process and the final NNUE play strength?
A. 100M position of depth 10
B. 100M position of depth 20
C. 1B position of depth 10
D. 1B position of depth 20
Let me guess, technically speaking, D > B > C > A ?

Yes, my intuition would be similar, though I rather guess C > B, but machine learning often isn't that clear cut, so might still end up differently in practice. From my experience increasing depth often does not help as much as you might think. Also depth 20 is quite extreme, I am not sure if people have the hardware to do that for 1B, since you need to consider that required search time goes up exponentially with depth (effective branching factors often are of the order of ~1.4 I think, so e.g. 1.4**10 = 29).

> Using the latest NNUE file to generate new training data, it's like the process of bootstrapping, will it cause Bootstrapping Error problem? i.e. If the latest NNUE weights and biases have weaknesses in some situations they will get amplified in the late nets.

Yes, that can happen. That is why it is hard to fix the endgame weaknesses just by further reinforcement learning, because it requires lots of iterations to correct consistent misevaluation. E.g., introducing some higher quality endgame data from different sources could help there.

> BTW, from your point of view, how much does the final NNUE file trained with depth 20 stronger than depth 10? What's the play strength difference between 1B position training data using the classical evaluation of depth 20 and 1B position with the latest NNUE net evaluation of depth 10?

It heavily depends. If playing strength already plateaus with the depth 10 training, then the difference can also be zero. It is very hard to predict.

> Furthermore, suppose I can't hold 1B position in the RAM at a time, I split them into 3 parts, 400M 300M 300M.
How much player strength difference it will be do you think in the following training process?
A. Training 1B at a time for 400 epochs.
B. Training 400M at a time for 400 epochs, continue training the following 300M position for 400 epochs and continue training the rest 300M for 400 epochs.

If I remember correctly the data is only read in (configurable) batches, so it won't read all data into memory at once.

> Finally, If I cause any inconvenience to you for taking your precious time to answer these questions, I am so sorry to bother you these days. ( >︿< )

If you can, joining our discord can be useful, because much more people are discussing there. But other than that there isn't anything wrong with asking good questions :).

**Comment by PikaCat-OuO** [comment]
Well, China, you know, for some reason, we can't access discord. Even access to Github is fits and starts since 2021.
> From my experience increasing depth often does not help as much as you might think. 

So there is little difference between 1B depth 10 and depth 20 training data result in the overall performance of the final nets? If that is the case, what's the optimal best max depth you think considering a 120 cores machine for data generation?

**Comment by ianfab** [comment]
If I knew the optimum I would tell you. As usual in machine learning it is a lot of trial and error to find out. But I would say 10 is already a quite decent depth, but if you have such strong hardware you might of course as well try with higher depth. When you use such high quality data it can then be very interesting to vary the lambda parameter of the training script. 1 means to only train on eval, 0 only on game result, and values in between a mix. Usually relatively high lambda are used (0.8-1), but especially when the games are of high quality training more based on game result might be promising, because that can fix long-term misevaluations. E.g., if it assumes that an endgame is drawn, but in the end is won by one side after good play from both sides, the game result likely is a more accurate evaluation of that endgame.

**Comment by PikaCat-OuO** [comment]
Thanks, that helps a lot.
