### ISSUE TITLE
Reinforcement learning on endgame result in bad opening and middle game performance.

### ISSUE THREAD

**Issue by PikaCat-OuO** [fairy-stockfish/variant-nnue-pytorch#18]
Suppose I trained the model with some high-quality endgame training_data.bin using the following command:
```bash
python serialize.py --features='HalfKAv2' xiangqi-6f64c55fcb28.nnue startingpointfortraining.pt 
python train.py --resume-from-model startingpointfortraining.pt --batch-size 8000 --threads 12 --num-workers 88 --gpus 1 --max_epochs 520 --lambda 0 training_data.bin validation_data.bin
```
After some tests, I found that the performance of the endgame has significantly improved but at the same time, the performance of the opening and the middle game is reduced dramatically.

So theoretically HalfKAv2 model has 8 buckets, the training may significantly affect the buckets for the endgame and not the buckets on the opening and middlegame. The only possible reason I could come up with is the endgame training changes the weight and biases of the feature transformer layer that lead to this bad result.

If my assumption is correct, what should I do to fix this issue? i.e. to improve the endgame performance while not affecting the opening and middle game performance greatly?

BTW, is there anything wrong with the command I'm using?

**Comment by ianfab** [comment]
Your command looks fine. Yes, I guess it should be the feature transformer that might get out of sync with the layers for the lower buckets, since the feature transformer changes but the other layers can't adapt if there is no training happening on them, so it might potentially even return close to random results. That is assuming your training data **only** contains endgames, which is how I understood it.

So in order to stabilize opening/middlegame performance one would need to try to prevent that from happening. Either by freezing the feature transformer, which I don't know if this is easily possible, or maybe by adding some "normal" data, so that it does not unlearn non-endgame positions. The latter should be the easiest solution and might be good enough already. A potential improvement to that would be to remove endgame positions from the "normal" data in order to avoid inconsistency with the better endgame evaluation.

Out of curiosity, what is the high-level endgame data you are using? Is it from different engines or from EGTBs?

**Comment by PikaCat-OuO** [comment]
> Out of curiosity, what is the high-level endgame data you are using? Is it from different engines or from EGTBs?

It's depth 10 data generated using the fairy-stockfish tools with an endgame position EPD.
As you said in https://github.com/fairy-stockfish/variant-nnue-pytorch/issues/16 10 is already a quite decent depth.

> That is assuming your training data only contains endgames, which is how I understood it.

Yes. And from the training result observation, the endgame performance of the result NNUE is quite good.

>  or maybe by adding some "normal" data, so that it does not unlearn non-endgame positions.

If I try this, how to deal with the "lambda"?
A:
Step 1: Train 100 epochs on "normal" data on lambda 0.8.
Step 2: Continue training 100 epochs on endgame data on lambda 0.
Go back to Step1?

B:
Mix the normal data and endgame data? But what about the "lambda"?

**Comment by ianfab** [comment]
Yeah, I didn't consider lambda. To me the most important would be to figure out how much stronger the new net is in the endgame, in order to be able to judge what might be required to make it surpass the current best net. E.g., one could compile a Fairy-SF version that only uses NNUE when there are less than N pieces (e.g. at https://github.com/ianfab/Fairy-Stockfish/blob/0683911b2f3e8ef75b5efd855bd5761b4b84bf57/src/position.h#L548) and run a match between the two nets.

Depending on how much better the new endgame eval is, there could be different option, e.g.
* Train your current net on normal data and high lambda but for not too many epochs in order to fix opening play but not destroy the endgame knowledge again.
* Generate endgame data using your net. This data should also work well with high lambda, assuming the net learned the endgames well. Assuming this, you can then merge this data with normal data and train it with high lambda.
  * Optionally filter out endgame positions from the normal data to reduce noise.
* Re-score endgame positions in normal training data using the new NNUE in order to merge the knowledge of the two nets. This would require some scripting.

So the smaller the improvement in the endgame evaluation, the more effort one might need to put in.

**Comment by PikaCat-OuO** [comment]
Yeah, bootstrapping can do good stuff, almost forget that, very smart ideas!
What about having a dedicated NNUE just for high-quality endgame data generation?

Again, thanks for helping me! ヾ(≧▽≦*)o

**Comment by ianfab** [comment]
Thanks. What were your test results? For me it seems to perform roughly on par with the current best network. When I manually check the endgame evaluation, it seems to be more accurate, but in overall game play I so far can't measure an improvement in playing strength.

```
f05cbc6a0213 vs 6f64c55fcb28

10''+0.1''
ELO: -0.87 +-26.4 (95%) LOS: 47.4%
Total: 400 W: 120 L: 121 D: 159

30''+0.3''
ELO: -0.00 +-52.2 (95%) LOS: 50.0%
Total: 100 W: 29 L: 29 D: 42
```

**Comment by PikaCat-OuO** [comment]
I'm curious, how do you perform the tests? Are you using the latest version of fairy stockfish?

**Comment by ianfab** [comment]
Yes, I use https://github.com/ianfab/variantfishtest with the books from https://github.com/ianfab/books and Fairy-SF dev. So what were your results in comparison?

**Comment by PikaCat-OuO** [comment]
<img width="213" alt="image" src="https://user-images.githubusercontent.com/73384062/176884634-1005ab88-3d97-4cbb-9806-a6d64215a704.png">

630m is f05cbc6a0213
510 is 6f64c55fcb28

The test result shows that 630M vs 510 W:72 D:43 L:7  The wining rate is 76.67%.
We are using a GUI for testing. Same engine different nets, 2 seconds per move.

**Comment by ianfab** [comment]
Since your net is very strong in the endgame, but potentially weaker in the opening, could it be that you are using a very deep opening book that basically makes games skip the opening phase? That currently is the only explanation I have for this huge discrepancy in results. A 10 to 1 win ratio is so significant that it normally should be very easy to reproduce.

**Comment by PikaCat-OuO** [comment]
Yes as you expected, we usually have an opening book in actual game playing. So we are more concerned about the midgame and endgame performance of the engine.
But more training and experiments are ongoing right now, we will have more nets that are more balanced in opening midgame endgame days later :)

**Comment by PikaCat-OuO** [comment]
Sorry for the lack of this knowledge. Thanks again for your info. 
Sorry again for taking your precious time to do this kind of meaning-less test :(

**Comment by ianfab** [comment]
It is good to see a net with a lot of potential. It just usually pays off to stick to the scientific approach of only accepting something new if there is significant evidence showing it is better. That not only applies to the algorithm (or NNUE network) itself, but also the method to compare/evaluate the algorithm. It could well be that a new patch, net, or testing condition is better than what there is before, but if you start using that as the standard without proving that it is better than the current best, then you have a gap in the chain of evidence, which opens up the possibility for regression. Of course outside of a stricly acedemic environment one does not have to be that rigorous, but as the Stockfish project has shown for chess it can be very pragmatic and beneficial to mostly stick to such a rigorous approach in order to eradicate human bias and overinterpretation.

**Comment by PikaCat-OuO** [comment]
Actually, I found out that many positions in the xiangqi.book are very weird looking. Such as:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/73384062/176997862-e6f8ba70-070b-4dd6-8868-4c2989113229.png">
There will be nobody playing this kind of xiangqi opening in China. Black rook 1 + 2 is very strange.

Another example:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/73384062/176997957-78f119d4-6e5c-4ab3-af53-28499a12501c.png">
It is just like pushing each side to exchange a knight in the opening. And the black rook and red rook just go off their position in order to make room for the exchange. Looks very strange in general.

As far as I know, China's top commercial xiangqi engines like bugchess and ccyclone will never use this kind of position for testing. They tend to use the 3-step position's from the cloud book(https://www.chessdb.cn/query_en/) with a score close enough to 0 like 1, 2, -1,-2, 3, etc... these two position's score is -47, and -18, which is not very close enough to 0.

BTW, in China's xiangqi engine competitions, they will follow the rule above. When two engines' levels are so close that they can't determine which one is better, they will use some deep opening book to skip the opening phase and directly go to the midgame phase and each engine takes turn to go first for yielding out a better engine. I believe that the testing method used in China is very different from that in other places like TCEC.

**Comment by ianfab** [comment]
If the scores you are referring to are in centipawns, I am surprised about how balanced the book is. The book is old and was filtered without NNUE, so there might be very unbalanced positions in there that are already almost winning, so I would have expected the worst positions to be more like 300. The book certainly could be improved, but getting perfectly equal positions isn't the goal. Since each position is played with both colors, no matter which positions are in the book there never is a bias.

The main criterion to optimize the set of positions is to squeeze out as much information as possible from each pair of games, which essentially corresponds to the entropy of the possible game results, or more generally the Elo sensitivity of the entire match. Since Xiangqi (just like Chess) tends to be drawish, positions should ideally be slightly unbalanced to get a more equal distribution between wins and draws to maximize the information you can draw from the results, but of course not too unbalanced because if both engines always win when getting the favorable side, you get zero information from it. Since this is not just a theory of mine but is supported by a decade of very successful Stockfish development, I think one at least can't go very wrong in following this.

I understand that the positions look awkward, and that is pretty much the same for all variants we are testing including standard chess. However, this ensures that there is enough variety, and as long as the positions are just awkward and not too unbalanced, they are fine as engine test positions. Using standard openings might seem more relevant, but then again you possibly run into overfitting problems and the engine might play badly when encountering unusual positions/structures.

**Comment by PikaCat-OuO** [comment]
> If the scores you are referring to are in centipawns, I am surprised about how balanced the book is.

Yes, the scores are in centipawn. And the following description is on the cloud book description:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/73384062/177000484-2c1f1bc2-7cd6-4b7a-a114-86494fc03bd9.png">

Actually, the scores are coming from the commercial engine ccyclone and they solve the problem of aggressive pruning and blind spots. The EGTB on the cloud book is also coming from ccyclone.
In addition, ccyclone is also an NNUE engine and it is currently ranked first among all xiangqi engines.

**Comment by PikaCat-OuO** [comment]
> The main criterion to optimize the set of positions is to squeeze out as much information as possible from each pair of games, which essentially corresponds to the entropy of the possible game results, or more generally the Elo sensitivity of the entire match. Since Xiangqi (just like Chess) tends to be drawish, positions should ideally be slightly unbalanced to get a more equal distribution between wins and draws to maximize the information you can draw from the results, but of course not too unbalanced because if both engines always win when getting the favorable side, you get zero information from it. Since this is not just a theory of mine but is supported by a decade of very successful Stockfish development, I think one at least can't go very wrong in following this.
> I understand that the positions look awkward, and that is pretty much the same for all variants we are testing including standard chess. However, this ensures that there is enough variety, and as long as the positions are just awkward and not too unbalanced, they are fine as engine test positions. Using standard openings might seem more relevant, but then again you possibly run into overfitting problems and the engine might play badly when encountering unusual positions/structures.

Fully understandable with the explanation :)

Again, a new net has been uploaded to google drive, what's the test result on your side to play against 6f64c55fcb28?

**Comment by ianfab** [comment]
Thanks. I ran a quick test and results look very consistent with yours. 
```
10+0.1
ELO: 57.86 +-35.7 (95%) LOS: 99.9%
Total: 200 W: 71 L: 38 D: 91
```

So considering that the net looks stable, I am happy to use it as the new standard net. I will then tomorrow update https://github.com/fairy-stockfish/Fairy-Stockfish-NNUE and https://github.com/fairy-stockfish/fairy-stockfish.github.io/blob/main/nnue.markdown with the new net, unless you want to create pull requests yourself. Please let me know which author name I should use in the list. Thanks for your contribution.

**Comment by PikaCat-OuO** [comment]
If Chinese characters are supported, use ```竹影听溪``` as the author's name.

> unless you want to create pull requests yourself

Well, just feel free to do it now, I will not create pull requests :)

**Comment by ianfab** [comment]
> If chinese characters are supported, use 竹影听溪 as the author's name.

Sure, it's now updated at https://fairy-stockfish.github.io/nnue/.

> Also, I'm very curious, even though the probability is very low, what if two NNUE files have the same leading 12 characters in SHA256. How do you name them?
Suppose an NNUE file has a SHA256 like abcdeabcde123456789.... and the other has a SHA256 like abcdeabcde129876543....
Do they both named nn-abcdeabced12.nnue?

In theory that can happen, but I will think about that when it occurs, likely not within the next 1000 years. :)

**Comment by PikaCat-OuO** [comment]
One more question, I have a detailed read on your answer in https://chess.stackexchange.com/questions/24685/why-does-fishtesting-test-stockfish-against-itself-not-other-engines/24714#24714 :)

When later nets come out, do we need to perform some regression tests on new nets against 6f64c55fcb28?

> The playing strength comparison of chess-playing entities usually does not fulfill transitivity
Also, if this is true, then why d134cdf48baf > 6f64c55fcb28 for 101 elo, 6f64c55fcb28 > classical evaluation for 640 elo, so d134cdf48baf > classical evaluation for 741 elo? It's not guarantee to fulfill transitivity.

**Comment by ianfab** [comment]
> When later nets come out, do we need to perform some regression tests on new nets against 6f64c55fcb28?

In theory we can't ensure transitivity, so there is a theoretical possibility that a new net might perform worse against an older net. However, in practice non-transitivity does not seem to be much of a problem, so regression testing against older versions is not critical, though of course never hurts.

This is also related to the earlier discussion about robust testing conditions, since transitivity issues are the more likely the less diversity there is in the games of the match. E.g., if you test without any opening book and match a handful of versions that are not too far apart in playing strength, you will likely already see examples of non-transitivity. So it mainly is a pragmatic assumption derived from experience that with robust testing conditions we don't need to worry much about transitivity, but in the end it still remains an assumption and might not always hold.

> >The playing strength comparison of chess-playing entities usually does not fulfill transitivity
> 
> Moreover, if this is true, then why d134cdf48baf > 6f64c55fcb28 for 101 elo, 6f64c55fcb28 > classical evaluation for 640 elo, so d134cdf48baf > classical evaluation for 741 elo? It's not guarantee to fulfill transitivity.

Yes, exactly, that is correct. Especially when Elo differences are big they almost never sum up linearly. However, the values specified there in the list are just approximations to have a ballpark number for the improvement of NNUE over classical evaluation, so this is not too much of a concern (what needs to be accurate is that the new net is better than the previous best, which is why we run the direct comparison there). It also is very hard to measure big playing strength differences (like 700 Elo) accurately, since you need a huge number of games, so direct comparison with classical evaluation is not very practicable. I used to have a short disclaimer in the old list (https://docs.google.com/spreadsheets/d/1fgGvBKleUOI1wZZbiNhpT98qhQ7mYuQ5kar1lTQ9g3w/edit?usp=sharing)
> Note: The diagram sums up the relative Elo improvements, but results might differ in direct comparison.

but apparently missed to write something similar in the new one.

**Comment by PikaCat-OuO** [comment]
I have noticed that in the train.py, the following code:
```python
def make_data_loaders(train_filename, val_filename, feature_set, num_workers, batch_size, filtered, random_fen_skipping, main_device):
  # Epoch and validation sizes are arbitrary
  epoch_size = 20000000
  val_size = 1000000
```
The epoch_size and val_size seem to be fixed. Does it mean that each epoch there are 20000000 data from the training data will be used?

**Comment by ianfab** [comment]
Yes, that's how it works if I remember correctly.
